apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: vote
  labels:
    app: db
spec:
  template:
    metadata:
      name: db
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
      volumes:
      - name: db-data
        emptyDir: {}
  # Especificações de controle de réplica        
  selector:
    matchLabels:
      # Bate com as labels definidas
      # Deve bate com a label: app definida no template
      app: db
  replicas: 1