apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    type: frontend
  ports:
    - name: http
      # Porta do POD
      port: 80
      # Porta que será exposta externamente em ambiente de desenv
      nodePort: 30080
  type: NodePort