apiVersion: v1
kind: Pod
metadata: 
  name: mysql-pod
  labels:
    app: mysql-app
spec:
  containers:
    - name: mysql-container
      image: mysql:5
      env:
         # Senha do usuário root
        - name: MYSQL_ROOT_PASSWORD
          value: pass
         # Nome do banco de dados 
        - name: MYSQL_DATABASE
          value: base-teste